### Products Index
GET http://localhost:3000/products.json

### Products Show
GET http://localhost:3000/products/8.json

### Products Create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "New Product",
  "price": "50",
  "image_url": "https://www.marketing91.com/wp-content/uploads/2018/08/Product-Portfolio-1.jpg",
  "description": "It's a product!"
}

### Products Update
PATCH http://localhost:3000/products/8.json
Content-Type: application/json

{
  "name": "renamed product"
}

### Products Destroy
DELETE http://localhost:3000/products/80.json