# Products

### Products Index
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc3MzM2ODd9.a6HhjZnZPyf-gpO71VrG4ga4V1RJPdGKURPJSRgHIcs

### Products Show
GET http://localhost:3000/products/1.json

### Products Create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "New Product 3",
  "price": "50",
  "image_url": "https://www.marketing91.com/wp-content/uploads/2018/08/Product-Portfolio-1.jpg",
  "description": "It's a product!"
}

### Products Update
PATCH http://localhost:3000/products/1.json
Content-Type: application/json

{
  "name": "masky boy",
  "price": "0"
}

### Products Destroy
DELETE http://localhost:3000/products/1.json



# Suppliers

### Suppliers Index
GET http://localhost:3000/suppliers.json

### Suppliers Show
GET http://localhost:3000/suppliers/1.json

### Suppliers Create
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "New Supplier",
  "email": "new@example.com",
  "phone_number": "555-555-5555"
}

### Suppliers Update        
PATCH http://localhost:3000/suppliers/1.json
Content-Type: application/json

{
  "phone_number": "000-000-0000"
}

### Suppliers Destroy
DELETE http://localhost:3000/suppliers/4.json



# Users

### Users Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Asher",
  "email": "asher@example.com",
  "password": "password",
  "password_confirmation": "password"
}



# Sessions

### Sessions Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "asher@example.com",
  "password": "password"
}



# Orders

### Orders Index
GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTc3Mzg0NjZ9.Llvvbdv0NqZAJOE19vLxI_bcFp3yDII0z7CLy_sxC2I

### Orders Show
GET http://localhost:3000/orders/27.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTc3MzgzMzN9.HGFUwlq8vOe0R4-p_EjsIMi2kBYTK33RJmDJSGO3OZI

### Orders Create
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTc3MzgzMzN9.HGFUwlq8vOe0R4-p_EjsIMi2kBYTK33RJmDJSGO3OZI
Content-Type: application/json

{
  "product_id": "1",
  "quantity": "5000"
}