@jwt_kay = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTgyNTQzNjR9.NzrFjxcEReIAxwggumkfQPSzJGSN2p02vTOM4STT_RE

# Products

### Products Index
GET http://localhost:3000/products.json

### Products Show
GET http://localhost:3000/products/1.json

### Products Create
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt_kay}}
Content-Type: application/json

{
  "name": "New Product 3",
  "price": "50",
  "description": "It's a product!",
  "supplier_id": 1
}

### Products Update
PATCH http://localhost:3000/products/1.json
Authorization: Bearer {{jwt_kay}}
Content-Type: application/json

{
  "name": "masky boy",
  "price": "0"
}

### Products Destroy
DELETE http://localhost:3000/products/1.json



# Suppliers

### Suppliers Index
GET http://localhost:3000/suppliers.json

### Suppliers Show
GET http://localhost:3000/suppliers/1.json

### Suppliers Create
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "New Supplier",
  "email": "new@example.com",
  "phone_number": "555-555-5555"
}

### Suppliers Update        
PATCH http://localhost:3000/suppliers/1.json
Content-Type: application/json

{
  "phone_number": "000-000-0000"
}

### Suppliers Destroy
DELETE http://localhost:3000/suppliers/4.json



# Users

### Users Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Asher",
  "email": "asher@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users Update
PATCH http://localhost:3000/users/1.json
Content-Type: application/json

{
  "admin": true
}



# Sessions

### Sessions Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "kay@example.com",
  "password": "password"
}



# Orders

### Orders Index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt_kay}}

### Orders Show
GET http://localhost:3000/orders/41.json
Authorization: Bearer {{jwt_kay}}

### Orders Create
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt_kay}}
Content-Type: application/json


# Carted Products

### Carted Product Index
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt_kay}}

### Carted Product Show
GET http://localhost:3000/carted_products/2.json
Authorization: Bearer {{jwt_kay}}

### Carted Product Create
POST http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt_kay}}
Content-Type: application/json

{
  "product_id": 4,
  "quantity": 15
}

### Carted Product Update
PATCH http://localhost:3000/carted_products/2.json
Authorization: Bearer {{jwt_kay}}
Content-Type: application/json

{
  "quantity": 15
}

### Carted Product Destroy
DELETE http://localhost:3000/carted_products/2.json
Authorization: Bearer {{jwt_kay}}
